// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: protomodule/proto/zetasql-extract-table.proto

package sqlanalyzer

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ExtractTableNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement string `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *ExtractTableNamesRequest) Reset() {
	*x = ExtractTableNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomodule_proto_zetasql_extract_table_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractTableNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTableNamesRequest) ProtoMessage() {}

func (x *ExtractTableNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protomodule_proto_zetasql_extract_table_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTableNamesRequest.ProtoReflect.Descriptor instead.
func (*ExtractTableNamesRequest) Descriptor() ([]byte, []int) {
	return file_protomodule_proto_zetasql_extract_table_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractTableNamesRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type ExtractTableNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableNames []string `protobuf:"bytes,1,rep,name=tableNames,proto3" json:"tableNames,omitempty"`
}

func (x *ExtractTableNamesResponse) Reset() {
	*x = ExtractTableNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomodule_proto_zetasql_extract_table_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractTableNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTableNamesResponse) ProtoMessage() {}

func (x *ExtractTableNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protomodule_proto_zetasql_extract_table_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTableNamesResponse.ProtoReflect.Descriptor instead.
func (*ExtractTableNamesResponse) Descriptor() ([]byte, []int) {
	return file_protomodule_proto_zetasql_extract_table_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractTableNamesResponse) GetTableNames() []string {
	if x != nil {
		return x.TableNames
	}
	return nil
}

var File_protomodule_proto_zetasql_extract_table_proto protoreflect.FileDescriptor

var file_protomodule_proto_zetasql_extract_table_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x65, 0x74, 0x61, 0x73, 0x71, 0x6c, 0x2d, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x2d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x73, 0x71, 0x6c, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x18,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x19, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x32, 0x6a, 0x0a, 0x11, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x55, 0x0a, 0x02, 0x44, 0x6f, 0x12, 0x25,
	0x2e, 0x73, 0x71, 0x6c, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x7a, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x4e, 0x0a, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x74, 0x6b, 0x74, 0x6b, 0x63, 0x37, 0x32, 0x2e, 0x73,
	0x71, 0x6c, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x42, 0x13, 0x5a, 0x65, 0x74, 0x61,
	0x73, 0x71, 0x6c, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x5a,
	0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6b, 0x74, 0x6b,
	0x63, 0x37, 0x32, 0x2f, 0x73, 0x71, 0x6c, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protomodule_proto_zetasql_extract_table_proto_rawDescOnce sync.Once
	file_protomodule_proto_zetasql_extract_table_proto_rawDescData = file_protomodule_proto_zetasql_extract_table_proto_rawDesc
)

func file_protomodule_proto_zetasql_extract_table_proto_rawDescGZIP() []byte {
	file_protomodule_proto_zetasql_extract_table_proto_rawDescOnce.Do(func() {
		file_protomodule_proto_zetasql_extract_table_proto_rawDescData = protoimpl.X.CompressGZIP(file_protomodule_proto_zetasql_extract_table_proto_rawDescData)
	})
	return file_protomodule_proto_zetasql_extract_table_proto_rawDescData
}

var file_protomodule_proto_zetasql_extract_table_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protomodule_proto_zetasql_extract_table_proto_goTypes = []interface{}{
	(*ExtractTableNamesRequest)(nil),  // 0: sqlanalyzer.ExtractTableNamesRequest
	(*ExtractTableNamesResponse)(nil), // 1: sqlanalyzer.ExtractTableNamesResponse
}
var file_protomodule_proto_zetasql_extract_table_proto_depIdxs = []int32{
	0, // 0: sqlanalyzer.ExtractTableNames.Do:input_type -> sqlanalyzer.ExtractTableNamesRequest
	1, // 1: sqlanalyzer.ExtractTableNames.Do:output_type -> sqlanalyzer.ExtractTableNamesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protomodule_proto_zetasql_extract_table_proto_init() }
func file_protomodule_proto_zetasql_extract_table_proto_init() {
	if File_protomodule_proto_zetasql_extract_table_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protomodule_proto_zetasql_extract_table_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractTableNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomodule_proto_zetasql_extract_table_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractTableNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protomodule_proto_zetasql_extract_table_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protomodule_proto_zetasql_extract_table_proto_goTypes,
		DependencyIndexes: file_protomodule_proto_zetasql_extract_table_proto_depIdxs,
		MessageInfos:      file_protomodule_proto_zetasql_extract_table_proto_msgTypes,
	}.Build()
	File_protomodule_proto_zetasql_extract_table_proto = out.File
	file_protomodule_proto_zetasql_extract_table_proto_rawDesc = nil
	file_protomodule_proto_zetasql_extract_table_proto_goTypes = nil
	file_protomodule_proto_zetasql_extract_table_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExtractTableNamesClient is the client API for ExtractTableNames service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExtractTableNamesClient interface {
	Do(ctx context.Context, in *ExtractTableNamesRequest, opts ...grpc.CallOption) (*ExtractTableNamesResponse, error)
}

type extractTableNamesClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractTableNamesClient(cc grpc.ClientConnInterface) ExtractTableNamesClient {
	return &extractTableNamesClient{cc}
}

func (c *extractTableNamesClient) Do(ctx context.Context, in *ExtractTableNamesRequest, opts ...grpc.CallOption) (*ExtractTableNamesResponse, error) {
	out := new(ExtractTableNamesResponse)
	err := c.cc.Invoke(ctx, "/sqlanalyzer.ExtractTableNames/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractTableNamesServer is the server API for ExtractTableNames service.
type ExtractTableNamesServer interface {
	Do(context.Context, *ExtractTableNamesRequest) (*ExtractTableNamesResponse, error)
}

// UnimplementedExtractTableNamesServer can be embedded to have forward compatible implementations.
type UnimplementedExtractTableNamesServer struct {
}

func (*UnimplementedExtractTableNamesServer) Do(context.Context, *ExtractTableNamesRequest) (*ExtractTableNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}

func RegisterExtractTableNamesServer(s *grpc.Server, srv ExtractTableNamesServer) {
	s.RegisterService(&_ExtractTableNames_serviceDesc, srv)
}

func _ExtractTableNames_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractTableNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractTableNamesServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sqlanalyzer.ExtractTableNames/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractTableNamesServer).Do(ctx, req.(*ExtractTableNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExtractTableNames_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sqlanalyzer.ExtractTableNames",
	HandlerType: (*ExtractTableNamesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _ExtractTableNames_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protomodule/proto/zetasql-extract-table.proto",
}
